name: hackathon

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_flavor: ^3.1.1
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^1.10.14
  flutter_riverpod: ^2.3.7
  freezed_annotation: ^2.4.1
  go_router: ^11.0.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  flutter_secure_storage: ^9.0.0
  dart_openai: ^4.0.0
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  flutter_native_splash: ^2.3.2
  sensors_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  pedantic_mono: ^1.24.0+1
  flutter_launcher_icons: ^0.13.1

flavorizr:
  flavors:
    dev:
      app:
        name: "FFFdev"
      android:
        applicationId: "com.fffan.hackathon.dev2023"  
      ios:
        bundleId: "com.fffan.hackathon.dev2023"
    prod:
      app:
        name: "FFF"
      android:
        applicationId: "com.fffan.hackathon2023"
      ios:
        bundleId: "com.fffan.hackathon2023"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  image_path: "assets/icons/FFF_icon.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  adaptive_icon_background: "#0F0F1C"

flutter_native_splash:
  color: "#42a5f5"