// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7jYfMQzqkmHy-lIBGgcyUq5Z7bMlb-W8',
    appId: '1:363379648313:android:216dc7aec831a1c88f6ae8',
    messagingSenderId: '363379648313',
    projectId: 'fff-hackathon-6a592',
    storageBucket: 'fff-hackathon-6a592.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtHZYzLa2F_kAg0grWYLV8Tw6vLNziJ6c',
    appId: '1:363379648313:ios:3f88ea74278760d28f6ae8',
    messagingSenderId: '363379648313',
    projectId: 'fff-hackathon-6a592',
    storageBucket: 'fff-hackathon-6a592.appspot.com',
    androidClientId: '363379648313-55qf29v5b1da5q90r1sof7t9a7hja8ij.apps.googleusercontent.com',
    iosClientId: '363379648313-pn5h69n6b4q1srskgab4c47r6c46fil5.apps.googleusercontent.com',
    iosBundleId: 'com.fffan.hackathon2023',
  );
}
